### PR TITLE
heisen_hang fixed, plus some additions to PyVQ

### PR DESCRIPTION
**Pull request by markyoder**
this merge really should fix the heisen_hang problem. note the commits near the end of may, early june. basically, replaced MPI_Send() with its synchronous cousin MPI_Ssend(), which specifically requires an MPI_Recv() handshake. also some new bits in PyVQ, including some greens value analysis tools. coming next: (off)diagonal specific GF filters, which should help with "Exploding_California".

### CODE REVIEW

**Comment by kwschultz** [comment]
well done sir

**Comment by eheien** [comment]
Very nice!

**Comment by markyoder** [comment]
indeed. still dialing in the Greens Function thresholds, but at least it's
running, more or less, stable.

how's San Jose treating you?

m

On Sun, Jun 7, 2015 at 9:54 PM, Eric Heien <notifications@github.com> wrote:

> Very nice!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/vq/pull/79#issuecomment-109861632>.
>



-- 
Mark Yoder, PhD
805 451 8750

"If you bore me, you lose your soul..."
~belly

**Comment by markyoder** [comment]
indeed. we still need to dial in those Greens Functions, but at least it's running and (more or less) stable.

**Pull request merged**
