### PR TITLE
Fix MPP Segmentation Fault and Linux installation

### PR DESCRIPTION
**Pull request by markyoder**
1) minor change to quakelib:QuakeLibUtil.h "include" to facilitate Linux installations (use relative include path, not absolute (mac) path).
2) several memory management, and variable initialization, and some minor bug fixes that seem to be causing instability in MPI mode.

### CODE REVIEW

**Comment by eheien** [comment]
Could you remove some of the debugging code that's commented out, and run 'astyle --options=astyle.rc --recursive "*.cpp" --recursive "*.h' to make the formatting consistent?  Thanks!

**Comment by markyoder** [comment]
ran astyle and pushed to my repo.

**Comment by kwschultz** [comment]
Is this good to go?

**Comment by markyoder** [comment]
let me go through it one more time. i've started some development since
then, but i think it's all been on a new branch.

m


On Mon, Mar 23, 2015 at 1:51 PM, Kasey Schultz <notifications@github.com>
wrote:

> Is this good to go?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/vq/pull/69#issuecomment-85190637>.
>



-- 
Mark Yoder, PhD
805 451 8750

"If you bore me, you lose your soul..."
~belly

**Comment by markyoder** [comment]
kasey -

this looks good to go from my perspective. as per eric's request, there is
probably debugging commentary yet to be removed, but since we're still
chasing down a couple of other bugs and since these changes are fresh, i'd
assume leave them in for now. as we go forward and these fixes are
confirmed (and so the comments are no longer relevant), we'll remove them.

tentatively, i think we're a few days away from another pull request to
incorporate these final_stress nan values, but there is evaluation yet to
be done there.

if you get a chance, you might run your own tests before approving the
merge. i think the criteria for this scope of work is that 1) it runs and
is stable in MPI mode, 2) debugging lines don't print to screen, 3) we get
output files (though the nan problem remains).

thanks.

m

On Mon, Mar 23, 2015 at 2:02 PM, Mark Yoder <mark.yoder@gmail.com> wrote:

> let me go through it one more time. i've started some development since
> then, but i think it's all been on a new branch.
>
> m
>
>
> On Mon, Mar 23, 2015 at 1:51 PM, Kasey Schultz <notifications@github.com>
> wrote:
>
>> Is this good to go?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/vq/pull/69#issuecomment-85190637>.
>>
>
>
>
> --
> Mark Yoder, PhD
> 805 451 8750
>
> "If you bore me, you lose your soul..."
> ~belly
>



-- 
Mark Yoder, PhD
805 451 8750

"If you bore me, you lose your soul..."
~belly

**Comment by markyoder** [comment]
still getting a "can't automatically merge" message, so i assume there are some conflicts which i'll get sorted out asap.

**Comment by markyoder** [comment]
a new, much improved pull request will be generated with many, many issues resolved.

**Pull request closed without merging**
