### PR TITLE
Add parallel build test in Bionic environment

### PR DESCRIPTION
**Pull request by tjesser-ucdavis-edu**
Depending on how Jenkins deals with parallel test results, this might not be worth merging. And it might not be worth testing on multiple environments anyway.

@johnmaxwilson I know you've been merging my PRs for the Jenkins build system, but are you fine with how it's working? As far as I know, you're currently the sole maintainer.

### CODE REVIEW

**Comment by tjesser-ucdavis-edu** [comment]
It seems like the DockerHub container autobuilds is working well. The DockerHub website provides good documentation on how they were built, the GitHub integration works well, and it's easy to get Jenkins to use them.

I guess the question is whether something needs to be changed in the Bionic container, or something needs to be changed in the VQ code.

**Comment by johnmaxwilson** [comment]
This is an issue that has cropped up frequently.  We might not have the dev time to put towards it until the beginning of the new quarter (at which time we'll be training a new student to come on board to take over), but troubleshooting these and other HDF5 issues on the side of the source code is a top priority.

**Comment by tjesser-ucdavis-edu** [comment]
Just checking to see if the timeline for 18.04 support has changed.

**Comment by johnmaxwilson** [comment]
The consultant we talked to said this would likely be fixed with a simple addition of a -lhdf5 flag when compiling

**Comment by johnmaxwilson** [comment]
This looks great, thanks for checking through the cmake docs.  Merging into base.

**Pull request merged**
